export const SCHOOLS = [
  { code: "AGNR", name: "Agriculture and Natural Resources" },
  { code: "ARCH", name: "School of Architecture, Planning and Preservation" },
  { code: "ARHU", name: "Arts and Humanities" },
  { code: "BMGT", name: "The Robert H. Smith School of Business" },
  { code: "BSOS", name: "Behavioral and Social Sciences" },
  { code: "CMNS", name: "Computer, Mathematical, and Natural Sciences" },
  { code: "EDUC", name: "Education" },
  { code: "ENGR", name: "The A. James Clark School of Engineering" },
  { code: "INFO", name: "Information" },
  { code: "JOUR", name: "Philip Merrill College of Journalism" },
  { code: "PLCY", name: "Public Policy" },
  { code: "SPHL", name: "School of Public Health" },
  { code: "UGST", name: "Undergraduate Studies" }
];

export const MAJORS = [
  { schoolCode: "AGNR", code: "AG BUS MGMT", name: "Agriculture Business Management" },
  { schoolCode: "AGNR", code: "AG LDR COMM", name: "Agricultural Leadership & Communication" },
  { schoolCode: "AGNR", code: "AG SCI &TECH", name: "Agricultural Science and Technology" },
  { schoolCode: "AGNR", code: "AG SCI&TECH", name: "Agricultural Science and Technology" },
  { schoolCode: "AGNR", code: "AG&RESRC-BUS", name: "Agricultural and Resource Economics: Agribusiness" },
  { schoolCode: "AGNR", code: "AG&RESRC-ECN", name: "Agricultural and Resource Economics: Env Res Econ" },
  { schoolCode: "AGNR", code: "AGR&RES ECON", name: "Agricultural and Resource Economics" },
  { schoolCode: "AGNR", code: "AGRI-APPLIED", name: "Agriculture - Applied" },
  { schoolCode: "AGNR", code: "AGST AGRO", name: "Agricultural Science & Tech: Agronomy" },
  { schoolCode: "AGNR", code: "AGST EDUC", name: "Agricultural Science & Tech: Agric & Extensn Educ" },
  { schoolCode: "AGNR", code: "AGST ENVHORT", name: "Agricultural Science & Tech: Environ Horticulture" },
  { schoolCode: "AGNR", code: "ANIMAL SCI", name: "Animal Sciences: Sciences/Preprofessional" },
  { schoolCode: "AGNR", code: "COM-AGRI-VET", name: "Combined-Agricultural and Veterinary Medicine" },
  { schoolCode: "AGNR", code: "ENST ECODESN", name: "Environmental Sci & Tech: Ecological Tech Design" },
  { schoolCode: "AGNR", code: "ENST ECOHLTH", name: "Environmental Sci & Tech: Ecosystem Health" },
  { schoolCode: "AGNR", code: "ENST RESMGMT", name: "Environmental Sci & Tech: Natural Resources Mgmt" },
  { schoolCode: "AGNR", code: "ENST SOILWTR", name: "Environmental Sci & Tech: Soil & Watershed Science" },
  { schoolCode: "AGNR", code: "ENST UNDEC", name: "Environmental Sci & Tech Undecided" },
  { schoolCode: "AGNR", code: "ENV S&P-EAGR", name: "Environmental Sci & Pol-Environment & Agriculture" },
  { schoolCode: "AGNR", code: "ENV S&P-ECON", name: "Environmental Sci & Pol-Env Economics" },
  { schoolCode: "AGNR", code: "ENV S&P-REST", name: "Environmental Sci & Pol-Env Restoration & Mgmt" },
  { schoolCode: "AGNR", code: "ENV S&P-SWLR", name: "Environmental Sci & Pol-Soil, Water & Land Rsrcs" },
  { schoolCode: "AGNR", code: "ENV S&P-WILD", name: "Environmental Sci & Pol-Wildlife Ecology & Mgmt" },
  { schoolCode: "AGNR", code: "ENV SCI&POL", name: "Environmental Science & Policy (Policy)" },
  { schoolCode: "AGNR", code: "ENV STWRDSHP", name: "Environmental Stewardship" },
  { schoolCode: "AGNR", code: "ENVIR/PARK", name: "Natural Resources Mgt: Envir Education & Park Mgmt" },
  { schoolCode: "AGNR", code: "FERMENT SCI", name: "Fermentation Science" },
  { schoolCode: "AGNR", code: "GEN ORN HORT", name: "General Ornamental Horticulture" },
  { schoolCode: "AGNR", code: "GLFCRS CONST", name: "Golf Course Construction Management" },
  { schoolCode: "AGNR", code: "GLOBL POVRTY", name: "Global Poverty" },
  { schoolCode: "AGNR", code: "GOLF CRS MGM", name: "Golf Course Management" },
  { schoolCode: "AGNR", code: "INT AG RES", name: "UG Certif: Intnatl Agriculture & Natural Resources" },
  { schoolCode: "AGNR", code: "LAND/WATER", name: "Natural Resources Mgt: Land & Water Mgmt" },
  { schoolCode: "AGNR", code: "LANDSCP MGMT", name: "Landscape Management" },
  { schoolCode: "AGNR", code: "LNDSCPE ARCH", name: "Landscape Architecture" },
  { schoolCode: "AGNR", code: "NFSC DIET", name: "Nutrition and Food Science: Dietetics" },
  { schoolCode: "AGNR", code: "NFSC FOODSCI", name: "Nutrition and Food Science: Food Science" },
  { schoolCode: "AGNR", code: "NFSC NUTRN", name: "Nutrition and Food Science: Nutritional Science" },
  { schoolCode: "AGNR", code: "PLANT/WILD", name: "Natural Resources Mgt: Plant & Wildlife Mgmt" },
  { schoolCode: "AGNR", code: "PLSC BIOL", name: "Plant Sciences: Plant Biology" },
  { schoolCode: "AGNR", code: "PLSC FOREST", name: "Plant Sciences: Urban Forestry" },
  { schoolCode: "AGNR", code: "PLSC HORT", name: "Plant Sciences: Horticulture & Crop Production" },
  { schoolCode: "AGNR", code: "PLSC TURF", name: "Plant Sciences: Turf & Golf Course Mgmt" },
  { schoolCode: "AGNR", code: "PRE-VET MED", name: "Pre-Veterinary Medicine" },
  { schoolCode: "AGNR", code: "SOIL SCIENCE", name: "Soil Science" },
  { schoolCode: "AGNR", code: "SPORT TURF", name: "Sports Turf Management" },
  { schoolCode: "AGNR", code: "SUSTAIN AG", name: "Sustainable Agriculture" },
  { schoolCode: "AGNR", code: "SUSTAIN STDY", name: "Sustainability Studies" },
  { schoolCode: "AGNR", code: "TRFGRASS MGM", name: "General Turfgrass Management" },
  { schoolCode: "AGNR", code: "URB FOR MGMT", name: "Urban Forest Management" },
  { schoolCode: "ARCH", code: "AI ARCH", name: "Artificial Intelligence in Architecture" },
  { schoolCode: "ARCH", code: "ARCH", name: "Architecture" },
  { schoolCode: "ARCH", code: "ARCH BA", name: "Architecture: B.A." },
  { schoolCode: "ARCH", code: "CONSTR PM", name: "Construction Project Management" },
  { schoolCode: "ARCH", code: "CRTVPLACEMKG", name: "Creative Placemaking" },
  { schoolCode: "ARCH", code: "HISTTHRYARCH", name: "History and Theory of Architecture" },
  { schoolCode: "ARCH", code: "RE DEVLOP", name: "Real Estate Development" },
  { schoolCode: "ARCH", code: "REALEST BENV", name: "Real Estate and the Built Environment" },
  { schoolCode: "ARHU", code: "AMER STUDIES", name: "American Studies" },
  { schoolCode: "ARHU", code: "ARABIC", name: "Arabic" },
  { schoolCode: "ARHU", code: "ARCHAEOLOGY", name: "Archaeology" },
  { schoolCode: "ARHU", code: "ART HISTORY", name: "Art History" },
  { schoolCode: "ARHU", code: "ART STUDIO", name: "Studio Art" },
  { schoolCode: "ARHU", code: "ARTS LDRSHIP", name: "Arts Leadership" },
  { schoolCode: "ARHU", code: "BLACK WMST", name: "Black Womens Studies" },
  { schoolCode: "ARHU", code: "CEN EUR STD", name: "Central European, Russian, and Eurasian Studies" },
  { schoolCode: "ARHU", code: "CHIN LANG", name: "Chinese Language" },
  { schoolCode: "ARHU", code: "CHIN STUDY", name: "Chinese Studies" },
  { schoolCode: "ARHU", code: "CHINESE", name: "Chinese" },
  { schoolCode: "ARHU", code: "CINEMA MEDIA", name: "Cinema and Media Studies" },
  { schoolCode: "ARHU", code: "CLASS MYTH", name: "Classical Mythology" },
  { schoolCode: "ARHU", code: "CLASSICS", name: "Classical Languages and Literatures" },
  { schoolCode: "ARHU", code: "COMM", name: "Communication" },
  { schoolCode: "ARHU", code: "CREATIVE WRT", name: "Creative Writing" },
  { schoolCode: "ARHU", code: "CRTVPLACEMKG", name: "Creative Placemaking" },
  { schoolCode: "ARHU", code: "DANCE", name: "Dance" },
  { schoolCode: "ARHU", code: "DIGSTORYPOET", name: "Digital Storytelling and Poetics" },
  { schoolCode: "ARHU", code: "EAST ASIAN", name: "UG Certif: East Asian Studies" },
  { schoolCode: "ARHU", code: "ENGLISH", name: "English" },
  { schoolCode: "ARHU", code: "FRENCH", name: "French Language and Literature" },
  { schoolCode: "ARHU", code: "FRENCH STDY", name: "French Studies" },
  { schoolCode: "ARHU", code: "GERMAN", name: "German Studies" },
  { schoolCode: "ARHU", code: "GERMNSTUDIES", name: "German Studies" },
  { schoolCode: "ARHU", code: "GLBC", name: "Global Culture and Thought" },
  { schoolCode: "ARHU", code: "GREEK", name: "Greek Language and Culture" },
  { schoolCode: "ARHU", code: "HEBRWSTUDIES", name: "Hebrew Studies" },
  { schoolCode: "ARHU", code: "HISTORY", name: "History" },
  { schoolCode: "ARHU", code: "HUM HLTH MED", name: "Humanities, Health, and Medicine" },
  { schoolCode: "ARHU", code: "IMDM EMRGCRT", name: "Immersive Media Design: Emerging Creatives-B.A." },
  { schoolCode: "ARHU", code: "ISRAEL STDY", name: "Israel Studies" },
  { schoolCode: "ARHU", code: "ITAL", name: "Italian Language and Culture" },
  { schoolCode: "ARHU", code: "ITAL STUDIES", name: "Italian Studies" },
  { schoolCode: "ARHU", code: "JAPANESE", name: "Japanese" },
  { schoolCode: "ARHU", code: "JEWISH STUDY", name: "Jewish Studies" },
  { schoolCode: "ARHU", code: "JWST", name: "Jewish Studies" },
  { schoolCode: "ARHU", code: "KORA STDY", name: "Korean Studies" },
  { schoolCode: "ARHU", code: "LACS", name: "UG Certif: Latin American and Caribbean Studies" },
  { schoolCode: "ARHU", code: "LAT GREK PB", name: "Latin and Greek Postbaccalaureate Program" },
  { schoolCode: "ARHU", code: "LATINO STUDY", name: "U.S. Latina/o Studies" },
  { schoolCode: "ARHU", code: "LATN", name: "Latin Language and Literature" },
  { schoolCode: "ARHU", code: "LATNAM CARIB", name: "Latin American and Caribbean Studies" },
  { schoolCode: "ARHU", code: "LGBTQ", name: "LGBTQ Studies" },
  { schoolCode: "ARHU", code: "LGBTQSTUDIES", name: "UG Certif: LGBTQ Studies" },
  { schoolCode: "ARHU", code: "LINGUISTICS", name: "Linguistics" },
  { schoolCode: "ARHU", code: "MID EAST STD", name: "Middle East Studies" },
  { schoolCode: "ARHU", code: "MUS LIB", name: "Music (Liberal Arts Program)" },
  { schoolCode: "ARHU", code: "MUS LIB JAZZ", name: "Music (Jazz Performance Option)" },
  { schoolCode: "ARHU", code: "MUS LIB PIAN", name: "Music (Piano Performance Option)" },
  { schoolCode: "ARHU", code: "MUS LIB STR", name: "Music (Strings Performance Option)" },
  { schoolCode: "ARHU", code: "MUS LIB VOIC", name: "Music (Voice Performance Option)" },
  { schoolCode: "ARHU", code: "MUS LIB WNDS", name: "Music (Winds & Percussions Performance Option)" },
  { schoolCode: "ARHU", code: "MUS PROF", name: "Music (Professional Program)" },
  { schoolCode: "ARHU", code: "MUS PROF CMP", name: "Music Composition" },
  { schoolCode: "ARHU", code: "MUS PROF JAZ", name: "Music Performance-Jazz Studies" },
  { schoolCode: "ARHU", code: "MUS PROF PIA", name: "Music Performance-Piano" },
  { schoolCode: "ARHU", code: "MUS PROF STR", name: "Music Performance-Strings" },
  { schoolCode: "ARHU", code: "MUS PROF THE", name: "Music Theory and Composition" },
  { schoolCode: "ARHU", code: "MUS PROF VOI", name: "Music Performance-Voice" },
  { schoolCode: "ARHU", code: "MUS PROF WND", name: "Music Performance-Winds and Percussion" },
  { schoolCode: "ARHU", code: "MUSIC CULTUR", name: "Music and Culture" },
  { schoolCode: "ARHU", code: "MUSIC ED", name: "Music Education" },
  { schoolCode: "ARHU", code: "MUSIC PERFOR", name: "Music Performance" },
  { schoolCode: "ARHU", code: "PERSIAN", name: "Persian Studies" },
  { schoolCode: "ARHU", code: "PERSIAN STDY", name: "Persian Studies" },
  { schoolCode: "ARHU", code: "PHILOSOPHY", name: "Philosophy" },
  { schoolCode: "ARHU", code: "PHILPOLIECON", name: "Philosophy, Politics, and Economics" },
  { schoolCode: "ARHU", code: "PORT BRAZLN", name: "Portuguese and Brazilian Studies" },
  { schoolCode: "ARHU", code: "PROF WRITING", name: "Professional Writing" },
  { schoolCode: "ARHU", code: "PSIT", name: "Public Service Interpreting and Translation" },
  { schoolCode: "ARHU", code: "RELANCMIDEAS", name: "Religions of the Ancient Middle East" },
  { schoolCode: "ARHU", code: "RELIG STUDY", name: "Religious Studies" },
  { schoolCode: "ARHU", code: "RHETORIC", name: "Rhetoric" },
  { schoolCode: "ARHU", code: "ROMA LANG", name: "Romance Languages" },
  { schoolCode: "ARHU", code: "RUSS STUDY", name: "Russian Studies" },
  { schoolCode: "ARHU", code: "RUSSIAN", name: "Russian Language and Literature" },
  { schoolCode: "ARHU", code: "SPAN1LITCULT", name: "Span Minor 1: Literature,Linguistics,Cultur" },
  { schoolCode: "ARHU", code: "SPAN2LANGPRO", name: "Span Minor 2: Lang, Culture,Profssnl Cntxts" },
  { schoolCode: "ARHU", code: "SPAN3HERITAG", name: "Span Minor 3: Heritage Lang Latino/a Cultr" },
  { schoolCode: "ARHU", code: "SPANISH", name: "Spanish Language, Literatures, and Cultures" },
  { schoolCode: "ARHU", code: "THEATRE", name: "Theatre" },
  { schoolCode: "ARHU", code: "WGSS", name: "Women, Gender, and Sexuality Studies" },
  { schoolCode: "ARHU", code: "WMNGNDRSXLTY", name: "Women, Gender, and Sexuality Studies" },
  { schoolCode: "BMGT", code: "ACCOUNTING", name: "Accounting" },
  { schoolCode: "BMGT", code: "ACCTG ADVSRY", name: "Accounting-Business Acct Advisory Track" },
  { schoolCode: "BMGT", code: "BMGT UNDEC", name: "Business-Undecided" },
  { schoolCode: "BMGT", code: "BUS ANALYTIC", name: "Business Analytics" },
  { schoolCode: "BMGT", code: "CMPTNLFINANC", name: "Computational Finance" },
  { schoolCode: "BMGT", code: "ENTRPRLDRSHP", name: "Entrepreneurial Leadership" },
  { schoolCode: "BMGT", code: "FINANCE", name: "Finance" },
  { schoolCode: "BMGT", code: "GEN BUS ADM", name: "General Business - Gateway" },
  { schoolCode: "BMGT", code: "GEN BUSINESS", name: "General Business" },
  { schoolCode: "BMGT", code: "INFO SYS", name: "Information Systems-Business" },
  { schoolCode: "BMGT", code: "INTNL BUSN", name: "International Business" },
  { schoolCode: "BMGT", code: "MARKETING", name: "Marketing" },
  { schoolCode: "BMGT", code: "MGMT", name: "Management" },
  { schoolCode: "BMGT", code: "MGMT ENTR", name: "Management-Entrepreneurship" },
  { schoolCode: "BMGT", code: "OM BA", name: "Operations Management and Business Analytics" },
  { schoolCode: "BMGT", code: "SUPP CH MGMT", name: "Supply Chain Management" },
  { schoolCode: "BSOS", code: "AFRCNSTUDIES", name: "African Studies" },
  { schoolCode: "BSOS", code: "AFRICANAMST", name: "African American and Africana Studies-Policy" },
  { schoolCode: "BSOS", code: "ANTH BS", name: "Anthropology-B.S." },
  { schoolCode: "BSOS", code: "ANTHROPOLOGY", name: "Anthropology-B.A." },
  { schoolCode: "BSOS", code: "ANTIBLKRACSM", name: "Anti-Black Racism" },
  { schoolCode: "BSOS", code: "BLACK WMST", name: "Black Womens Studies" },
  { schoolCode: "BSOS", code: "BSOS UNDECID", name: "BSOS Undecided" },
  { schoolCode: "BSOS", code: "CRIM-JUSTICE", name: "Criminology and Criminal Justice" },
  { schoolCode: "BSOS", code: "CRIMJUST", name: "Criminal Justice" },
  { schoolCode: "BSOS", code: "DEMOGRAPHY", name: "Demography" },
  { schoolCode: "BSOS", code: "ECONOMICS", name: "Economics" },
  { schoolCode: "BSOS", code: "ECONOMICS-BS", name: "Economics-B.S." },
  { schoolCode: "BSOS", code: "ENV S&P-CULT", name: "Environmental Sci & Pol-Culture and the Environmnt" },
  { schoolCode: "BSOS", code: "ENV S&P-ECON", name: "Environmental Sci & Pol-Env Economics" },
  { schoolCode: "BSOS", code: "ENV S&P-GLOB", name: "Environmental Sci & Pol-Global Environmntl Change" },
  { schoolCode: "BSOS", code: "ENV S&P-LAND", name: "Environmental Sci & Pol-Land Use" },
  { schoolCode: "BSOS", code: "ENV S&P-MARN", name: "Environmental Sci & Pol-Marine & Coastal Mgmt" },
  { schoolCode: "BSOS", code: "ENV S&P-PLTC", name: "Environmental Sci & Pol-Env Politics & Policy" },
  { schoolCode: "BSOS", code: "ENV S&P-SCTY", name: "Environmental Sci & Pol-Society & Env Issues" },
  { schoolCode: "BSOS", code: "GEO CMP ERTH", name: "Geographical Sciences: Computatnl Earth Obsvtn Sci" },
  { schoolCode: "BSOS", code: "GEO DATA SCI", name: "Geographical Sciences: Geospatial Data Science" },
  { schoolCode: "BSOS", code: "GEO INFO SCI", name: "Geographic Information Science" },
  { schoolCode: "BSOS", code: "GEO SCIENCES", name: "Geographical Sciences" },
  { schoolCode: "BSOS", code: "GLBLTERRSTDY", name: "Global Terrorism Studies" },
  { schoolCode: "BSOS", code: "GOVT & POLIT", name: "Government & Politics" },
  { schoolCode: "BSOS", code: "GVPT BS", name: "Government & Politics: B.S." },
  { schoolCode: "BSOS", code: "HEAR+SPCH SC", name: "Hearing and Speech Sciences" },
  { schoolCode: "BSOS", code: "HESP", name: "Hearing and Speech Sciences" },
  { schoolCode: "BSOS", code: "HESPIE", name: "Hearing and Speech Postbaccalaureate Program" },
  { schoolCode: "BSOS", code: "INTL CONFLMG", name: "International Development & Conflict Mgmt" },
  { schoolCode: "BSOS", code: "INTLREL", name: "International Relations" },
  { schoolCode: "BSOS", code: "INTLREL BS", name: "International Relations-BS" },
  { schoolCode: "BSOS", code: "LAW SOCIETY", name: "Law and Society" },
  { schoolCode: "BSOS", code: "MID EAST STD", name: "Middle East Studies" },
  { schoolCode: "BSOS", code: "NEURO BEHAV", name: "Neuroscience: Behavioral & Cognitive Track" },
  { schoolCode: "BSOS", code: "NEUROSCIENCE", name: "Neuroscience" },
  { schoolCode: "BSOS", code: "PSYCH BS", name: "Psychology-B.S." },
  { schoolCode: "BSOS", code: "PSYCHOLOGY", name: "Psychology" },
  { schoolCode: "BSOS", code: "SDSC AFAMST", name: "Social Data Science-African American Studies" },
  { schoolCode: "BSOS", code: "SDSC ANTH", name: "Social Data Science-Anthropology" },
  { schoolCode: "BSOS", code: "SDSC ECON", name: "Social Data Science-Economics" },
  { schoolCode: "BSOS", code: "SDSC GEOG", name: "Social Data Science-Geographical Sciences" },
  { schoolCode: "BSOS", code: "SDSC GVPT", name: "Social Data Science-Government and Politics" },
  { schoolCode: "BSOS", code: "SDSC PSYC", name: "Social Data Science-Psychology" },
  { schoolCode: "BSOS", code: "SDSC SOCY", name: "Social Data Science-Sociology" },
  { schoolCode: "BSOS", code: "SENS ENV CH", name: "Remote Sensing of Environmental Change" },
  { schoolCode: "BSOS", code: "SOCIOLOGY", name: "Sociology" },
  { schoolCode: "BSOS", code: "SOCY", name: "Sociology" },
  { schoolCode: "BSOS", code: "SURV METHOD", name: "Survey Methodology" },
  { schoolCode: "CMNS", code: "ACTUARL MATH", name: "Actuarial Mathematics" },
  { schoolCode: "CMNS", code: "AOSC", name: "Atmospheric and Oceanic Science" },
  { schoolCode: "CMNS", code: "ASTRONOMY", name: "Astronomy" },
  { schoolCode: "CMNS", code: "ATMOSPH CHEM", name: "Atmospheric Chemistry" },
  { schoolCode: "CMNS", code: "ATMOSPH SCI", name: "Atmospheric Sciences" },
  { schoolCode: "CMNS", code: "BIO SCI:BIVS", name: "Biological Sciences: Individualized Studies" },
  { schoolCode: "CMNS", code: "BIO SCI:CEBG", name: "Biological Sciences: Cell Biology & Genetics" },
  { schoolCode: "CMNS", code: "BIO SCI:ECEV", name: "Biological Sciences: Ecology & Evolution" },
  { schoolCode: "CMNS", code: "BIO SCI:GENB", name: "Biological Sciences: General Biology" },
  { schoolCode: "CMNS", code: "BIO SCI:MICB", name: "Biological Sciences: Microbiology" },
  { schoolCode: "CMNS", code: "BIO SCI:PHNB", name: "Biological Sciences: Physiology & Neurobiology" },
  { schoolCode: "CMNS", code: "BIOCHEMISTRY", name: "Biochemistry" },
  { schoolCode: "CMNS", code: "CHEMISTRY BA", name: "Chemistry: B.A." },
  { schoolCode: "CMNS", code: "CHEMISTRY BS", name: "Chemistry: B.S." },
  { schoolCode: "CMNS", code: "CLIMATE CHG", name: "Climate Change Fluency" },
  { schoolCode: "CMNS", code: "CMSC", name: "Computer Science" },
  { schoolCode: "CMNS", code: "CMSC CSECRTY", name: "Computer Science-Cybersecurity Track" },
  { schoolCode: "CMNS", code: "CMSC DATASCI", name: "Computer Science-Data Science Track" },
  { schoolCode: "CMNS", code: "CMSC EDUC", name: "Computer Science-Education Track" },
  { schoolCode: "CMNS", code: "CMSC MACHINE", name: "Computer Science-Machine Learning Track" },
  { schoolCode: "CMNS", code: "CMSC QUANTUM", name: "Computer Science-Quantum Information" },
  { schoolCode: "CMNS", code: "COMPTNL SCI", name: "UG Certif: Computational Science" },
  { schoolCode: "CMNS", code: "COMPUTER SCI", name: "Computer Science" },
  { schoolCode: "CMNS", code: "DATA SCIENCE", name: "Data Science" },
  { schoolCode: "CMNS", code: "EARTH HIST", name: "Earth History" },
  { schoolCode: "CMNS", code: "EARTH MATER", name: "Earth Material Properties" },
  { schoolCode: "CMNS", code: "ENTOMOLOGY", name: "Entomology" },
  { schoolCode: "CMNS", code: "ENV S&P-BIOD", name: "Environmental Sci & Pol-Biodvrsity & Conserv Bio" },
  { schoolCode: "CMNS", code: "ENV S&P-ERTH", name: "Environmental Sci & Pol-Earth Surface Proc" },
  { schoolCode: "CMNS", code: "ENV S&P-GEO", name: "Environmental Sci & Pol-Env Geosci and Restoration" },
  { schoolCode: "CMNS", code: "GEOCHEMISTRY", name: "Geochemistry" },
  { schoolCode: "CMNS", code: "GEOL GEOPHYS", name: "Geology-Geophysics Track" },
  { schoolCode: "CMNS", code: "GEOLEARTHENV", name: "Geology-Earth and Env Sciences Track" },
  { schoolCode: "CMNS", code: "GEOLOGY", name: "Geology" },
  { schoolCode: "CMNS", code: "GEOPHYSICS", name: "Geophysics" },
  { schoolCode: "CMNS", code: "HYDROLOGY", name: "Hydrology" },
  { schoolCode: "CMNS", code: "IMDM CMSC", name: "Immersive Media Design: Computing-B.S." },
  { schoolCode: "CMNS", code: "MATH", name: "Mathematics" },
  { schoolCode: "CMNS", code: "MATH-APPLIED", name: "Mathematics-Applied Math track" },
  { schoolCode: "CMNS", code: "MATH-ED", name: "Mathematics-Secondary Ed track" },
  { schoolCode: "CMNS", code: "MATH-STAT", name: "Mathematics-Statistics Track" },
  { schoolCode: "CMNS", code: "MATHEMATICS", name: "Mathematics" },
  { schoolCode: "CMNS", code: "METEOROLOGY", name: "Meteorology" },
  { schoolCode: "CMNS", code: "NEURO MOLEC", name: "Neuroscience: Molecular, Cellular, & Physio Track" },
  { schoolCode: "CMNS", code: "NEUROSCIENCE", name: "Neuroscience" },
  { schoolCode: "CMNS", code: "PALEOBIOLOGY", name: "Paleobiology" },
  { schoolCode: "CMNS", code: "PHYS-APPL", name: "Physics-Applied" },
  { schoolCode: "CMNS", code: "PHYS-BIOPHYS", name: "Physics-Biophysics" },
  { schoolCode: "CMNS", code: "PHYS-EDUC", name: "Physics-Education" },
  { schoolCode: "CMNS", code: "PHYSICS", name: "Physics" },
  { schoolCode: "CMNS", code: "PLANET SCI", name: "Planetary Sciences" },
  { schoolCode: "CMNS", code: "PSCI", name: "Physical Sciences" },
  { schoolCode: "CMNS", code: "SIE", name: "Life Science Postbaccalaureate Program" },
  { schoolCode: "CMNS", code: "STATISTICS", name: "Statistics" },
  { schoolCode: "CMNS", code: "SURFIC GEOL", name: "Surficial Geology" },
  { schoolCode: "CMNS", code: "UMB NURSING", name: "Nursing (UMB Program)" },
  { schoolCode: "EDUC", code: "ASL", name: "American Sign Language (ASL)" },
  { schoolCode: "EDUC", code: "DISABLTYSTDY", name: "Disability Studies" },
  { schoolCode: "EDUC", code: "EC-ECSE-PRE", name: "Early Childhood and EC Special Education (Pre)" },
  { schoolCode: "EDUC", code: "EC-ECSE-PRO", name: "Early Childhood and EC Special Education" },
  { schoolCode: "EDUC", code: "ED-ELEM-PRE", name: "Elementary Education (Pre)" },
  { schoolCode: "EDUC", code: "ED-ELEM-PRO", name: "Elementary Education" },
  { schoolCode: "EDUC", code: "ED-SPEC-PRE", name: "Special Education (Pre)" },
  { schoolCode: "EDUC", code: "ED-SPEC-PRO", name: "Special Education" },
  { schoolCode: "EDUC", code: "EDS-ART-PRE", name: "Secondary Educ: Art (Pre)" },
  { schoolCode: "EDUC", code: "EDS-ART-PRO", name: "Secondary Educ: Art Education" },
  { schoolCode: "EDUC", code: "EDS-ENGL-PRE", name: "Secondary Educ: English Language Arts (Pre)" },
  { schoolCode: "EDUC", code: "EDS-ENGL-PRO", name: "Secondary Educ: English Language Arts" },
  { schoolCode: "EDUC", code: "EDS-LANG-PRE", name: "Secondary Educ: World Language Education (Pre)" },
  { schoolCode: "EDUC", code: "EDS-LANG-PRO", name: "Secondary Educ: World Language Education" },
  { schoolCode: "EDUC", code: "EDS-MATH-PRE", name: "Secondary Educ: Mathematics (Pre)" },
  { schoolCode: "EDUC", code: "EDS-MATH-PRO", name: "Secondary Educ: Mathematics" },
  { schoolCode: "EDUC", code: "EDS-SCI-PRE", name: "Secondary Educ: Science (Pre)" },
  { schoolCode: "EDUC", code: "EDS-SCI-PRO", name: "Secondary Educ: Science" },
  { schoolCode: "EDUC", code: "EDS-SS-PRE", name: "Secondary Educ: Social Studies (Pre)" },
  { schoolCode: "EDUC", code: "EDS-SS-PRO", name: "Secondary Educ: Social Studies" },
  { schoolCode: "EDUC", code: "EDUC-UNDECID", name: "Undecided Teacher Education" },
  { schoolCode: "EDUC", code: "EPEJ", name: "Education Policy, Equity, and Justice" },
  { schoolCode: "EDUC", code: "HUMAN DEV", name: "Human Development" },
  { schoolCode: "EDUC", code: "HUMAN DVLPMT", name: "Human Development" },
  { schoolCode: "EDUC", code: "LDRSHIP STDY", name: "Leadership Studies" },
  { schoolCode: "EDUC", code: "LDRSHP STDY", name: "UG Certif: Leadership Studies" },
  { schoolCode: "EDUC", code: "MSE", name: "Middle School Education" },
  { schoolCode: "EDUC", code: "MSE PRE", name: "Middle School Education (Pre)" },
  { schoolCode: "EDUC", code: "SECOND ED", name: "UG Certif: Secondary Education" },
  { schoolCode: "EDUC", code: "SECOND EDUC", name: "Secondary Education" },
  { schoolCode: "EDUC", code: "SPEC EDUC", name: "Special Education" },
  { schoolCode: "EDUC", code: "TERPS-EXCEED", name: "Terps-EXCEED" },
  { schoolCode: "EDUC", code: "TESOLDUALANG", name: "Tchg Engl for Spkrs of Oth Lang&Dual Lang Ed" },
  { schoolCode: "ENGR", code: "BIO ENGR", name: "Engineering: Bioengineering" },
  { schoolCode: "ENGR", code: "BIOCENGR PRE", name: "Biocomp Engr-PRE-MAJOR" },
  { schoolCode: "ENGR", code: "BIOCOMP ENGR", name: "Biocomputational Engineering" },
  { schoolCode: "ENGR", code: "COMP ENGIN", name: "Engineering: Computer" },
  { schoolCode: "ENGR", code: "COMP ENGR", name: "Computer Engineering" },
  { schoolCode: "ENGR", code: "CONSTR PM", name: "Construction Project Management" },
  { schoolCode: "ENGR", code: "CY PHYS PRE", name: "Cyber-Physical Systems Engineering-PRE-MAJOR" },
  { schoolCode: "ENGR", code: "CYBRPHYSENGR", name: "Cyber-Physical Systems Engineering" },
  { schoolCode: "ENGR", code: "ENGIN-UNDECI", name: "Engineering: Undecided" },
  { schoolCode: "ENGR", code: "ENGR-AEROSP", name: "Engineering: Aerospace" },
  { schoolCode: "ENGR", code: "ENGR-CHEM", name: "Engineering: Chemical" },
  { schoolCode: "ENGR", code: "ENGR-CIVIL", name: "Engineering: Civil" },
  { schoolCode: "ENGR", code: "ENGR-ELEC", name: "Engineering: Electrical" },
  { schoolCode: "ENGR", code: "ENGR-FIRE", name: "Engineering: Fire Protection (online)" },
  { schoolCode: "ENGR", code: "ENGR-MECH", name: "Engineering: Mechanical" },
  { schoolCode: "ENGR", code: "GLBL ENGRLDR", name: "Global Engineering Leadership" },
  { schoolCode: "ENGR", code: "MAT SCI&ENGR", name: "Engineering: Materials Science" },
  { schoolCode: "ENGR", code: "MECHATRN PRE", name: "Mechatronics Engineering-PRE-MAJOR" },
  { schoolCode: "ENGR", code: "MECHATRNENGR", name: "Mechatronics Engineering" },
  { schoolCode: "ENGR", code: "NANO TECH", name: "Nanoscale Science and Technology" },
  { schoolCode: "ENGR", code: "NUCLEAR ENGR", name: "Nuclear Engineering" },
  { schoolCode: "ENGR", code: "PROJ MGMT", name: "Project Management" },
  { schoolCode: "ENGR", code: "QSE", name: "Quantum Science and Engineering" },
  { schoolCode: "ENGR", code: "RAS", name: "Robotics and Autonomous Systems" },
  { schoolCode: "ENGR", code: "TECH ENTRPNR", name: "Tech Entrepreneurship & Corporate Innovatn" },
  { schoolCode: "ENGR", code: "VEP", name: "Veterans Pathways Program" },
  { schoolCode: "INFO", code: "INFO SCI", name: "Information Science" },
  { schoolCode: "INFO", code: "INFORISKETH", name: "Information Risk Mgmt, Ethics, and Privacy" },
  { schoolCode: "INFO", code: "SDSC", name: "Social Data Science" },
  { schoolCode: "INFO", code: "TECHINFODESN", name: "Technology and Information Design" },
  { schoolCode: "INFO", code: "TECHINNOVLDR", name: "Technology Innovation Leadership (online)" },
  { schoolCode: "JOUR", code: "JOURNALISM", name: "Journalism: News/Editorial" },
  { schoolCode: "JOUR", code: "MEDIATECHDEM", name: "Media, Technology and Democracy" },
  { schoolCode: "JOUR", code: "VIDEODOCUMNT", name: "Video Production and Documentary Filmmaking" },
  { schoolCode: "PLCY", code: "GLBLFOR PLCY", name: "Global and Foreign Policy" },
  { schoolCode: "PLCY", code: "NONPRFLDRSHP", name: "Nonprofit Leadership and Social Innovation" },
  { schoolCode: "PLCY", code: "PUB LDRSHIP", name: "Public Leadership" },
  { schoolCode: "PLCY", code: "PUB POLICY", name: "Public Policy" },
  { schoolCode: "PLCY", code: "STEP", name: "Science, Technology, Ethics and Policy" },
  { schoolCode: "PLCY", code: "SUSTAIN STDY", name: "Sustainability Studies" },
  { schoolCode: "SPHL", code: "BIOMECH MTRC", name: "Kinesiology:Biomechanics & Motor Control" },
  { schoolCode: "SPHL", code: "COMM HEALTH", name: "Community Health" },
  { schoolCode: "SPHL", code: "ENV S&P-JUST", name: "Environmental Sci & Pol-Environmental Justice" },
  { schoolCode: "SPHL", code: "EXER PHYSIO", name: "Kinesiology:Exercise Physiology" },
  { schoolCode: "SPHL", code: "FAMILY HLTH", name: "Family Health" },
  { schoolCode: "SPHL", code: "GLOBAL HLTH", name: "Global Health" },
  { schoolCode: "SPHL", code: "KINESIOLOGY", name: "Kinesiology" },
  { schoolCode: "SPHL", code: "PHYS ED", name: "Physical Education" },
  { schoolCode: "SPHL", code: "PUB HLTH SCI", name: "Public Health Science" },
  { schoolCode: "SPHL", code: "PUBHLTH PRAC", name: "Public Health Practice" },
  { schoolCode: "SPHL", code: "SDSC PUBHLTH", name: "Social Data Science-Public Health" },
  { schoolCode: "SPHL", code: "SPHL UNDECID", name: "SPHL Undecided" },
  { schoolCode: "SPHL", code: "SPORT", name: "Sport Commerce and Culture" },
  { schoolCode: "SPHL", code: "SPRTCOMMCULT", name: "Kinesiology:Sport, Commerce, & Culture" },
  { schoolCode: "UGST", code: "ACA ACH PROG", name: "Academic Achievement Programs" },
  { schoolCode: "UGST", code: "ACES", name: "Advanced Cybersecurity Experience for Stds" },
  { schoolCode: "UGST", code: "ARMYLDRSHP", name: "Army Leadership Studies" },
  { schoolCode: "UGST", code: "ASIAN AM ST", name: "Asian American Studies" },
  { schoolCode: "UGST", code: "ASIAN AMER", name: "UG Certif: Asian American Studies" },
  { schoolCode: "UGST", code: "CONCURRENTHS", name: "Concurrent HS" },
  { schoolCode: "UGST", code: "INDIV STUDY", name: "Individual Studies" },
  { schoolCode: "UGST", code: "MILITARYSTDY", name: "Military Studies" },
  { schoolCode: "UGST", code: "MTAP", name: "Maryland Transfer Advantage Program" },
  { schoolCode: "UGST", code: "NAVALSCIENCE", name: "Naval Science" },
  { schoolCode: "UGST", code: "PRE-DENT", name: "Combined Program-Dentistry" },
  { schoolCode: "UGST", code: "PRE-LAW", name: "Combined Program-Law" }
];

export const MAJOR_COMPOUND_TO_NAME: Record<string, string> = {
  "AGNR|AG BUS MGMT": "Agriculture Business Management",
  "AGNR|AG LDR COMM": "Agricultural Leadership & Communication",
  "AGNR|AG SCI &TECH": "Agricultural Science and Technology",
  "AGNR|AG SCI&TECH": "Agricultural Science and Technology",
  "AGNR|AG&RESRC-BUS": "Agricultural and Resource Economics: Agribusiness",
  "AGNR|AG&RESRC-ECN": "Agricultural and Resource Economics: Env Res Econ",
  "AGNR|AGR&RES ECON": "Agricultural and Resource Economics",
  "AGNR|AGRI-APPLIED": "Agriculture - Applied",
  "AGNR|AGST AGRO": "Agricultural Science & Tech: Agronomy",
  "AGNR|AGST EDUC": "Agricultural Science & Tech: Agric & Extensn Educ",
  "AGNR|AGST ENVHORT": "Agricultural Science & Tech: Environ Horticulture",
  "AGNR|ANIMAL SCI": "Animal Sciences: Animal Care & Management",
  "AGNR|COM-AGRI-VET": "Combined-Agricultural and Veterinary Medicine",
  "AGNR|ENST ECODESN": "Environmental Sci & Tech: Ecological Tech Design",
  "AGNR|ENST ECOHLTH": "Environmental Sci & Tech: Ecosystem Health",
  "AGNR|ENST RESMGMT": "Environmental Sci & Tech: Natural Resources Mgmt",
  "AGNR|ENST SOILWTR": "Environmental Sci & Tech: Soil & Watershed Science",
  "AGNR|ENST UNDEC": "Environmental Sci & Tech Undecided",
  "AGNR|ENV S&P-EAGR": "Environmental Sci & Pol-Environment & Agriculture",
  "AGNR|ENV S&P-ECON": "Environmental Sci & Pol-Env Economics",
  "AGNR|ENV S&P-REST": "Environmental Sci & Pol-Env Restoration & Mgmt",
  "AGNR|ENV S&P-SWLR": "Environmental Sci & Pol-Soil, Water & Land Rsrcs",
  "AGNR|ENV S&P-WILD": "Environmental Sci & Pol-Wildlife Ecology & Mgmt",
  "AGNR|ENV SCI&POL": "Environmental Science & Policy",
  "AGNR|ENV STWRDSHP": "Environmental Stewardship",
  "AGNR|ENVIR/PARK": "Natural Resources Mgt: Envir Education & Park Mgmt",
  "AGNR|FERMENT SCI": "Fermentation Science",
  "AGNR|GEN ORN HORT": "General Ornamental Horticulture",
  "AGNR|GLFCRS CONST": "Golf Course Construction Management",
  "AGNR|GLOBL POVRTY": "Global Poverty",
  "AGNR|GOLF CRS MGM": "Golf Course Management",
  "AGNR|INT AG RES": "UG Certif: Intnatl Agriculture & Natural Resources",
  "AGNR|LAND/WATER": "Natural Resources Mgt: Land & Water Mgmt",
  "AGNR|LANDSCP MGMT": "Landscape Management",
  "AGNR|LNDSCPE ARCH": "Landscape Architecture",
  "AGNR|NFSC DIET": "Nutrition and Food Science: Dietetics",
  "AGNR|NFSC FOODSCI": "Nutrition and Food Science: Food Science",
  "AGNR|NFSC NUTRN": "Nutrition and Food Science: Nutritional Science",
  "AGNR|PLANT/WILD": "Natural Resources Mgt: Plant & Wildlife Mgmt",
  "AGNR|PLSC BIOL": "Plant Sciences: Plant Biology",
  "AGNR|PLSC FOREST": "Plant Sciences: Urban Forestry",
  "AGNR|PLSC HORT": "Plant Sciences: Horticulture & Crop Production",
  "AGNR|PLSC TURF": "Plant Sciences: Turf & Golf Course Mgmt",
  "AGNR|PRE-VET MED": "Pre-Veterinary Medicine",
  "AGNR|SOIL SCIENCE": "Soil Science",
  "AGNR|SPORT TURF": "Sports Turf Management",
  "AGNR|SUSTAIN AG": "Sustainable Agriculture",
  "AGNR|SUSTAIN STDY": "Sustainability Studies",
  "AGNR|TRFGRASS MGM": "General Turfgrass Management",
  "AGNR|URB FOR MGMT": "Urban Forest Management",
  "ARCH|AI ARCH": "Artificial Intelligence in Architecture",
  "ARCH|ARCH": "Architecture",
  "ARCH|ARCH BA": "Architecture: B.A.",
  "ARCH|CONSTR PM": "Construction Project Management",
  "ARCH|CRTVPLACEMKG": "Creative Placemaking",
  "ARCH|HISTTHRYARCH": "History and Theory of Architecture",
  "ARCH|RE DEVLOP": "Real Estate Development",
  "ARCH|REALEST BENV": "Real Estate and the Built Environment",
  "ARHU|AMER STUDIES": "American Studies",
  "ARHU|ARABIC": "Arabic Studies",
  "ARHU|ARCHAEOLOGY": "Archaeology",
  "ARHU|ART HISTORY": "Art History",
  "ARHU|ART STUDIO": "Studio Art",
  "ARHU|ARTS LDRSHIP": "Arts Leadership",
  "ARHU|BLACK WMST": "Black Womens Studies",
  "ARHU|CEN EUR STD": "Central European, Russian, and Eurasian Studies",
  "ARHU|CHIN LANG": "Chinese Language",
  "ARHU|CHIN STUDY": "Chinese Studies",
  "ARHU|CHINESE": "Chinese",
  "ARHU|CINEMA MEDIA": "Cinema and Media Studies",
  "ARHU|CLASS MYTH": "Classical Mythology",
  "ARHU|CLASSICS": "Classical Languages and Literatures",
  "ARHU|COMM": "Communication",
  "ARHU|CREATIVE WRT": "Creative Writing",
  "ARHU|CRTVPLACEMKG": "Creative Placemaking",
  "ARHU|DANCE": "Dance",
  "ARHU|DIGSTORYPOET": "Digital Storytelling and Poetics",
  "ARHU|EAST ASIAN": "UG Certif: East Asian Studies",
  "ARHU|ENGLISH": "English Language and Literature",
  "ARHU|FRENCH": "French Language and Literature",
  "ARHU|FRENCH STDY": "French Studies",
  "ARHU|GERMAN": "German Studies",
  "ARHU|GERMNSTUDIES": "German Studies",
  "ARHU|GLBC": "Global Culture and Thought",
  "ARHU|GREEK": "Greek Language and Culture",
  "ARHU|HEBRWSTUDIES": "Hebrew Studies",
  "ARHU|HISTORY": "History",
  "ARHU|HUM HLTH MED": "Humanities, Health, and Medicine",
  "ARHU|IMDM EMRGCRT": "Immersive Media Design: Emerging Creatives-B.A.",
  "ARHU|ISRAEL STDY": "Israel Studies",
  "ARHU|ITAL": "Italian Language and Culture",
  "ARHU|ITAL STUDIES": "Italian Studies",
  "ARHU|JAPANESE": "Japanese",
  "ARHU|JEWISH STUDY": "Jewish Studies",
  "ARHU|JWST": "Jewish Studies",
  "ARHU|KORA STDY": "Korean Studies",
  "ARHU|LACS": "UG Certif: Latin American and Caribbean Studies",
  "ARHU|LAT GREK PB": "Latin and Greek Postbaccalaureate Program",
  "ARHU|LATINO STUDY": "U.S. Latina/o Studies",
  "ARHU|LATN": "Latin Language and Literature",
  "ARHU|LATNAM CARIB": "Latin American and Caribbean Studies",
  "ARHU|LGBTQ": "LGBTQ Studies",
  "ARHU|LGBTQSTUDIES": "UG Certif: LGBTQ Studies",
  "ARHU|LINGUISTICS": "Linguistics",
  "ARHU|MID EAST STD": "Middle East Studies",
  "ARHU|MUS LIB": "Music (Liberal Arts Program)",
  "ARHU|MUS LIB JAZZ": "Music (Jazz Performance Option)",
  "ARHU|MUS LIB PIAN": "Music (Piano Performance Option)",
  "ARHU|MUS LIB STR": "Music (Strings Performance Option)",
  "ARHU|MUS LIB VOIC": "Music (Voice Performance Option)",
  "ARHU|MUS LIB WNDS": "Music (Winds & Percussions Performance Option)",
  "ARHU|MUS PROF": "Music (Professional Program)",
  "ARHU|MUS PROF CMP": "Music Composition",
  "ARHU|MUS PROF JAZ": "Music Performance-Jazz Studies",
  "ARHU|MUS PROF PIA": "Music Performance-Piano",
  "ARHU|MUS PROF STR": "Music Performance-Strings",
  "ARHU|MUS PROF THE": "Music Theory and Composition",
  "ARHU|MUS PROF VOI": "Music Performance-Voice",
  "ARHU|MUS PROF WND": "Music Performance-Winds and Percussion",
  "ARHU|MUSIC CULTUR": "Music and Culture",
  "ARHU|MUSIC ED": "Music Education",
  "ARHU|MUSIC PERFOR": "Music Performance",
  "ARHU|PERSIAN": "Persian Studies",
  "ARHU|PERSIAN STDY": "Persian Studies",
  "ARHU|PHILOSOPHY": "Philosophy",
  "ARHU|PHILPOLIECON": "Philosophy, Politics, and Economics",
  "ARHU|PORT BRAZLN": "Portuguese and Brazilian Studies",
  "ARHU|PROF WRITING": "Professional Writing",
  "ARHU|PSIT": "Public Service Interpreting and Translation",
  "ARHU|RELANCMIDEAS": "Religions of the Ancient Middle East",
  "ARHU|RELIG STUDY": "Religious Studies",
  "ARHU|RHETORIC": "Rhetoric",
  "ARHU|ROMA LANG": "Romance Languages",
  "ARHU|RUSS STUDY": "Russian Studies",
  "ARHU|RUSSIAN": "Russian Language and Literature",
  "ARHU|SPAN1LITCULT": "Span Minor 1: Literature,Linguistics,Cultur",
  "ARHU|SPAN2LANGPRO": "Span Minor 2: Lang, Culture,Profssnl Cntxts",
  "ARHU|SPAN3HERITAG": "Span Minor 3: Heritage Lang Latino/a Cultr",
  "ARHU|SPANISH": "Spanish Language, Literatures, and Cultures",
  "ARHU|THEATRE": "Theatre",
  "ARHU|WGSS": "Women, Gender, and Sexuality Studies",
  "ARHU|WMNGNDRSXLTY": "UG Certif: Women, Gender, and Sexuality Studies",
  "BMGT|ACCOUNTING": "Accounting",
  "BMGT|ACCTG ADVSRY": "Accounting-Business Acct Advisory Track",
  "BMGT|BMGT UNDEC": "Business-Undecided",
  "BMGT|BUS ANALYTIC": "Business Analytics",
  "BMGT|CMPTNLFINANC": "Computational Finance",
  "BMGT|ENTRPRLDRSHP": "Entrepreneurial Leadership",
  "BMGT|FINANCE": "Finance",
  "BMGT|GEN BUS ADM": "General Business - Gateway",
  "BMGT|GEN BUSINESS": "General Business",
  "BMGT|INFO SYS": "Information Systems-Business",
  "BMGT|INTNL BUSN": "International Business",
  "BMGT|MARKETING": "Marketing",
  "BMGT|MGMT": "Management",
  "BMGT|MGMT ENTR": "Management-Entrepreneurship",
  "BMGT|OM BA": "Operations Management and Business Analytics",
  "BMGT|SUPP CH MGMT": "Supply Chain Management",
  "BSOS|AFRCNSTUDIES": "African Studies",
  "BSOS|AFRICANAMST": "African American and Africana Studies",
  "BSOS|ANTH BS": "Anthropology-B.S.",
  "BSOS|ANTHROPOLOGY": "Anthropology-B.A.",
  "BSOS|ANTIBLKRACSM": "Anti-Black Racism",
  "BSOS|BLACK WMST": "Black Womens Studies",
  "BSOS|BSOS UNDECID": "BSOS Undecided",
  "BSOS|CRIM-JUSTICE": "Criminology and Criminal Justice",
  "BSOS|CRIMJUST": "Criminal Justice",
  "BSOS|DEMOGRAPHY": "Demography",
  "BSOS|ECONOMICS": "Economics",
  "BSOS|ECONOMICS-BS": "Economics-B.S.",
  "BSOS|ENV S&P-CULT": "Environmental Sci & Pol-Culture and the Environmnt",
  "BSOS|ENV S&P-ECON": "Environmental Sci & Pol-Env Economics",
  "BSOS|ENV S&P-GLOB": "Environmental Sci & Pol-Global Environmntl Change",
  "BSOS|ENV S&P-LAND": "Environmental Sci & Pol-Land Use",
  "BSOS|ENV S&P-MARN": "Environmental Sci & Pol-Marine & Coastal Mgmt",
  "BSOS|ENV S&P-PLTC": "Environmental Sci & Pol-Env Politics & Policy",
  "BSOS|ENV S&P-SCTY": "Environmental Sci & Pol-Society & Env Issues",
  "BSOS|GEO CMP ERTH": "Geographical Sciences: Computatnl Earth Obsvtn Sci",
  "BSOS|GEO DATA SCI": "Geographical Sciences: Geospatial Data Science",
  "BSOS|GEO INFO SCI": "Geographic Information Science",
  "BSOS|GEO SCIENCES": "Geographical Sciences",
  "BSOS|GLBLTERRSTDY": "Global Terrorism Studies",
  "BSOS|GOVT & POLIT": "Government & Politics",
  "BSOS|GVPT BS": "Government & Politics: B.S.",
  "BSOS|HEAR+SPCH SC": "Hearing and Speech Sciences",
  "BSOS|HESP": "Hearing and Speech Sciences",
  "BSOS|HESPIE": "Hearing and Speech Postbaccalaureate Prog (online)",
  "BSOS|INTL CONFLMG": "International Development & Conflict Mgmt",
  "BSOS|INTLREL": "International Relations",
  "BSOS|INTLREL BS": "International Relations-BS",
  "BSOS|LAW SOCIETY": "Law and Society",
  "BSOS|MID EAST STD": "Middle East Studies",
  "BSOS|NEURO BEHAV": "Neuroscience: Behavioral & Cognitive Track",
  "BSOS|NEUROSCIENCE": "Neuroscience",
  "BSOS|PSYCH BS": "Psychology-B.S.",
  "BSOS|PSYCHOLOGY": "Psychology",
  "BSOS|SDSC AFAMST": "Social Data Science-African American Studies",
  "BSOS|SDSC ANTH": "Social Data Science-Anthropology",
  "BSOS|SDSC ECON": "Social Data Science-Economics",
  "BSOS|SDSC GEOG": "Social Data Science-Geographical Sciences",
  "BSOS|SDSC GVPT": "Social Data Science-Government and Politics",
  "BSOS|SDSC PSYC": "Social Data Science-Psychology",
  "BSOS|SDSC SOCY": "Social Data Science-Sociology",
  "BSOS|SENS ENV CH": "Remote Sensing of Environmental Change",
  "BSOS|SOCIOLOGY": "Sociology",
  "BSOS|SOCY": "Sociology",
  "BSOS|SURV METHOD": "Survey Methodology",
  "CMNS|ACTUARL MATH": "Actuarial Mathematics",
  "CMNS|AOSC": "Atmospheric and Oceanic Science",
  "CMNS|ASTRONOMY": "Astronomy",
  "CMNS|ATMOSPH CHEM": "Atmospheric Chemistry",
  "CMNS|ATMOSPH SCI": "Atmospheric Sciences",
  "CMNS|BIO SCI:BIVS": "Biological Sciences: Individualized Studies",
  "CMNS|BIO SCI:CEBG": "Biological Sciences: Cell Biology & Genetics",
  "CMNS|BIO SCI:ECEV": "Biological Sciences: Ecology & Evolution",
  "CMNS|BIO SCI:GENB": "Biological Sciences: General Biology",
  "CMNS|BIO SCI:MICB": "Biological Sciences: Microbiology",
  "CMNS|BIO SCI:PHNB": "Biological Sciences: Physiology & Neurobiology",
  "CMNS|BIOCHEMISTRY": "Biochemistry",
  "CMNS|CHEMISTRY BA": "Chemistry: B.A.",
  "CMNS|CHEMISTRY BS": "Chemistry: B.S.",
  "CMNS|CLIMATE CHG": "Climate Change Fluency",
  "CMNS|CMSC": "Computer Science",
  "CMNS|CMSC CSECRTY": "Computer Science-Cybersecurity Track",
  "CMNS|CMSC DATASCI": "Computer Science-Data Science Track",
  "CMNS|CMSC EDUC": "Computer Science-Education Track",
  "CMNS|CMSC MACHINE": "Computer Science-Machine Learning Track",
  "CMNS|CMSC QUANTUM": "Computer Science-Quantum Information",
  "CMNS|COMPTNL SCI": "UG Certif: Computational Science",
  "CMNS|COMPUTER SCI": "Computer Science",
  "CMNS|DATA SCIENCE": "Data Science",
  "CMNS|EARTH HIST": "Earth History",
  "CMNS|EARTH MATER": "Earth Material Properties",
  "CMNS|ENTOMOLOGY": "Entomology",
  "CMNS|ENV S&P-BIOD": "Environmental Sci & Pol-Biodvrsity & Conserv Bio",
  "CMNS|ENV S&P-ERTH": "Environmental Sci & Pol-Earth Surface Proc",
  "CMNS|ENV S&P-GEO": "Environmental Sci & Pol-Env Geosci and Restoration",
  "CMNS|GEOCHEMISTRY": "Geochemistry",
  "CMNS|GEOL GEOPHYS": "Geology-Geophysics Track",
  "CMNS|GEOLEARTHENV": "Geology-Earth and Env Sciences Track",
  "CMNS|GEOLOGY": "Geology",
  "CMNS|GEOPHYSICS": "Geophysics",
  "CMNS|HYDROLOGY": "Hydrology",
  "CMNS|IMDM CMSC": "Immersive Media Design: Computing-B.S.",
  "CMNS|MATH": "Mathematics",
  "CMNS|MATH-APPLIED": "Mathematics-Applied Math track",
  "CMNS|MATH-ED": "Mathematics-Secondary Ed track",
  "CMNS|MATH-STAT": "Mathematics-Statistics Track",
  "CMNS|MATHEMATICS": "Mathematics",
  "CMNS|METEOROLOGY": "Meteorology",
  "CMNS|NEURO MOLEC": "Neuroscience: Molecular, Cellular, & Physio Track",
  "CMNS|NEUROSCIENCE": "Neuroscience",
  "CMNS|PALEOBIOLOGY": "Paleobiology",
  "CMNS|PHYS-APPL": "Physics-Applied",
  "CMNS|PHYS-BIOPHYS": "Physics-Biophysics",
  "CMNS|PHYS-EDUC": "Physics-Education",
  "CMNS|PHYSICS": "Physics",
  "CMNS|PLANET SCI": "Planetary Sciences",
  "CMNS|PSCI": "Physical Sciences",
  "CMNS|SIE": "Life Science Postbaccalaureate Program",
  "CMNS|STATISTICS": "Statistics",
  "CMNS|SURFIC GEOL": "Surficial Geology",
  "CMNS|UMB NURSING": "Nursing (UMB Program)",
  "EDUC|ASL": "American Sign Language (ASL)",
  "EDUC|DISABLTYSTDY": "Disability Studies",
  "EDUC|EC-ECSE-PRE": "Early Childhood and EC Special Education (Pre)",
  "EDUC|EC-ECSE-PRO": "Early Childhood and EC Special Education",
  "EDUC|ED-ELEM-PRE": "Elementary Education (Pre)",
  "EDUC|ED-ELEM-PRO": "Elementary Education",
  "EDUC|ED-SPEC-PRE": "Special Education (Pre)",
  "EDUC|ED-SPEC-PRO": "Special Education",
  "EDUC|EDS-ART-PRE": "Secondary Educ: Art (Pre)",
  "EDUC|EDS-ART-PRO": "Secondary Educ: Art Education",
  "EDUC|EDS-ENGL-PRE": "Secondary Educ: English Language Arts (Pre)",
  "EDUC|EDS-ENGL-PRO": "Secondary Educ: English Language Arts",
  "EDUC|EDS-LANG-PRE": "Secondary Educ: World Language Education (Pre)",
  "EDUC|EDS-LANG-PRO": "Secondary Educ: World Language Education",
  "EDUC|EDS-MATH-PRE": "Secondary Educ: Mathematics (Pre)",
  "EDUC|EDS-MATH-PRO": "Secondary Educ: Mathematics",
  "EDUC|EDS-SCI-PRE": "Secondary Educ: Science (Pre)",
  "EDUC|EDS-SCI-PRO": "Secondary Educ: Science",
  "EDUC|EDS-SS-PRE": "Secondary Educ: Social Studies (Pre)",
  "EDUC|EDS-SS-PRO": "Secondary Educ: Social Studies",
  "EDUC|EDUC-UNDECID": "Undecided Teacher Education",
  "EDUC|EPEJ": "Education Policy, Equity, and Justice",
  "EDUC|HUMAN DEV": "Human Development",
  "EDUC|HUMAN DVLPMT": "Human Development",
  "EDUC|LDRSHIP STDY": "Leadership Studies",
  "EDUC|LDRSHP STDY": "UG Certif: Leadership Studies",
  "EDUC|MSE": "Middle School Education",
  "EDUC|MSE PRE": "Middle School Education (Pre)",
  "EDUC|SECOND ED": "UG Certif: Secondary Education",
  "EDUC|SECOND EDUC": "Secondary Education",
  "EDUC|SPEC EDUC": "Special Education",
  "EDUC|TERPS-EXCEED": "Terps-EXCEED",
  "EDUC|TESOLDUALANG": "Tchg Engl for Spkrs of Oth Lang&Dual Lang Ed",
  "ENGR|BIO ENGR": "Engineering: Bioengineering",
  "ENGR|BIOCENGR PRE": "Biocomp Engr-PRE-MAJOR",
  "ENGR|BIOCOMP ENGR": "Biocomputational Engineering",
  "ENGR|COMP ENGIN": "Engineering: Computer",
  "ENGR|COMP ENGR": "Computer Engineering",
  "ENGR|CONSTR PM": "Construction Project Management",
  "ENGR|CY PHYS PRE": "Cyber-Physical Systems Engineering-PRE-MAJOR",
  "ENGR|CYBRPHYSENGR": "Cyber-Physical Systems Engineering",
  "ENGR|ENGIN-UNDECI": "Engineering: Undecided",
  "ENGR|ENGR-AEROSP": "Engineering: Aerospace",
  "ENGR|ENGR-CHEM": "Engineering: Chemical",
  "ENGR|ENGR-CIVIL": "Engineering: Civil",
  "ENGR|ENGR-ELEC": "Engineering - Electrical",
  "ENGR|ENGR-FIRE": "Engineering: Fire Protection",
  "ENGR|ENGR-MECH": "Engineering: Mechanical",
  "ENGR|GLBL ENGRLDR": "Global Engineering Leadership",
  "ENGR|MAT SCI&ENGR": "Engineering: Materials Science",
  "ENGR|MECHATRN PRE": "Mechatronics Engineering-PRE-MAJOR",
  "ENGR|MECHATRNENGR": "Mechatronics Engineering",
  "ENGR|NANO TECH": "Nanoscale Science and Technology",
  "ENGR|NUCLEAR ENGR": "Nuclear Engineering",
  "ENGR|PROJ MGMT": "Project Management",
  "ENGR|QSE": "Quantum Science and Engineering",
  "ENGR|RAS": "Robotics and Autonomous Systems",
  "ENGR|TECH ENTRPNR": "Tech Entrepreneurship & Corporate Innovatn",
  "ENGR|VEP": "Veterans Pathways Program",
  "INFO|INFO SCI": "Information Science",
  "INFO|INFORISKETH": "Information Risk Mgmt, Ethics, and Privacy",
  "INFO|SDSC": "Social Data Science",
  "INFO|TECHINFODESN": "Technology and Information Design",
  "INFO|TECHINNOVLDR": "Technology Innovation Leadership (online)",
  "JOUR|JOURNALISM": "Journalism Undecided",
  "JOUR|MEDIATECHDEM": "Media, Technology and Democracy",
  "JOUR|VIDEODOCUMNT": "Video Production and Documentary Filmmaking",
  "PLCY|GLBLFOR PLCY": "Global and Foreign Policy",
  "PLCY|NONPRFLDRSHP": "Nonprofit Leadership and Social Innovation",
  "PLCY|PUB LDRSHIP": "Public Leadership",
  "PLCY|PUB POLICY": "Public Policy",
  "PLCY|STEP": "Science, Technology, Ethics and Policy",
  "PLCY|SUSTAIN STDY": "Sustainability Studies",
  "SPHL|BIOMECH MTRC": "Kinesiology:Biomechanics & Motor Control",
  "SPHL|COMM HEALTH": "Community Health",
  "SPHL|ENV S&P-JUST": "Environmental Sci & Pol-Environmental Justice",
  "SPHL|EXER PHYSIO": "Kinesiology:Exercise Physiology",
  "SPHL|FAMILY HLTH": "Family Health",
  "SPHL|GLOBAL HLTH": "Global Health",
  "SPHL|KINESIOLOGY": "Kinesiology",
  "SPHL|PHYS ED": "Physical Education",
  "SPHL|PUB HLTH SCI": "Public Health Science",
  "SPHL|PUBHLTH PRAC": "Public Health Practice",
  "SPHL|SDSC PUBHLTH": "Social Data Science-Public Health",
  "SPHL|SPHL UNDECID": "SPHL Undecided",
  "SPHL|SPORT": "Sport Commerce and Culture",
  "SPHL|SPRTCOMMCULT": "Kinesiology:Sport, Commerce, & Culture",
  "UGST|ACA ACH PROG": "Academic Achievement Programs",
  "UGST|ACES": "Advanced Cybersecurity Experience for Stds",
  "UGST|ARMYLDRSHP": "Army Leadership Studies",
  "UGST|ASIAN AM ST": "Asian American Studies",
  "UGST|ASIAN AMER": "UG Certif: Asian American Studies",
  "UGST|CONCURRENTHS": "Concurrent HS",
  "UGST|INDIV STUDY": "Individual Studies",
  "UGST|MILITARYSTDY": "Military Studies",
  "UGST|MTAP": "Maryland Transfer Advantage Program",
  "UGST|NAVALSCIENCE": "Naval Science",
  "UGST|PRE-DENT": "Combined Program-Dentistry",
  "UGST|PRE-LAW": "Combined Program-Law"
};

export const MAJOR_CODE_TO_NAME: Record<string, string> = {
  "ACA ACH PROG": "Academic Achievement Programs",
  "ACCOUNTING": "Accounting",
  "ACCTG ADVSRY": "Accounting-Business Acct Advisory Track",
  "ACES": "Advanced Cybersecurity Experience for Stds",
  "ACTUARL MATH": "Actuarial Mathematics",
  "AFRCNSTUDIES": "African Studies",
  "AFRICANAMST": "African American and Africana Studies-Policy",
  "AG BUS MGMT": "Agriculture Business Management",
  "AG LDR COMM": "Agricultural Leadership & Communication",
  "AG SCI &TECH": "Agricultural Science and Technology",
  "AG SCI&TECH": "Agricultural Science and Technology",
  "AG&RESRC-BUS": "Agricultural and Resource Economics: Agribusiness",
  "AG&RESRC-ECN": "Agricultural and Resource Economics: Env Res Econ",
  "AGR&RES ECON": "Agricultural and Resource Economics",
  "AGRI-APPLIED": "Agriculture - Applied",
  "AGST AGRO": "Agricultural Science & Tech: Agronomy",
  "AGST EDUC": "Agricultural Science & Tech: Agric & Extensn Educ",
  "AGST ENVHORT": "Agricultural Science & Tech: Environ Horticulture",
  "AI ARCH": "Artificial Intelligence in Architecture",
  "AMER STUDIES": "American Studies",
  "ANIMAL SCI": "Animal Sciences: Sciences/Preprofessional",
  "ANTH BS": "Anthropology-B.S.",
  "ANTHROPOLOGY": "Anthropology-B.A.",
  "ANTIBLKRACSM": "Anti-Black Racism",
  "AOSC": "Atmospheric and Oceanic Science",
  "ARABIC": "Arabic",
  "ARCH": "Architecture",
  "ARCH BA": "Architecture: B.A.",
  "ARCHAEOLOGY": "Archaeology",
  "ARMYLDRSHP": "Army Leadership Studies",
  "ART HISTORY": "Art History",
  "ART STUDIO": "Studio Art",
  "ARTS LDRSHIP": "Arts Leadership",
  "ASIAN AM ST": "Asian American Studies",
  "ASIAN AMER": "UG Certif: Asian American Studies",
  "ASL": "American Sign Language (ASL)",
  "ASTRONOMY": "Astronomy",
  "ATMOSPH CHEM": "Atmospheric Chemistry",
  "ATMOSPH SCI": "Atmospheric Sciences",
  "BIO ENGR": "Engineering: Bioengineering",
  "BIO SCI:BIVS": "Biological Sciences: Individualized Studies",
  "BIO SCI:CEBG": "Biological Sciences: Cell Biology & Genetics",
  "BIO SCI:ECEV": "Biological Sciences: Ecology & Evolution",
  "BIO SCI:GENB": "Biological Sciences: General Biology",
  "BIO SCI:MICB": "Biological Sciences: Microbiology",
  "BIO SCI:PHNB": "Biological Sciences: Physiology & Neurobiology",
  "BIOCENGR PRE": "Biocomp Engr-PRE-MAJOR",
  "BIOCHEMISTRY": "Biochemistry",
  "BIOCOMP ENGR": "Biocomputational Engineering",
  "BIOMECH MTRC": "Kinesiology:Biomechanics & Motor Control",
  "BLACK WMST": "Black Womens Studies",
  "BMGT UNDEC": "Business-Undecided",
  "BSOS UNDECID": "BSOS Undecided",
  "BUS ANALYTIC": "Business Analytics",
  "CEN EUR STD": "Central European, Russian, and Eurasian Studies",
  "CHEMISTRY BA": "Chemistry: B.A.",
  "CHEMISTRY BS": "Chemistry: B.S.",
  "CHIN LANG": "Chinese Language",
  "CHIN STUDY": "Chinese Studies",
  "CHINESE": "Chinese",
  "CINEMA MEDIA": "Cinema and Media Studies",
  "CLASS MYTH": "Classical Mythology",
  "CLASSICS": "Classical Languages and Literatures",
  "CLIMATE CHG": "Climate Change Fluency",
  "CMPTNLFINANC": "Computational Finance",
  "CMSC": "Computer Science",
  "CMSC CSECRTY": "Computer Science-Cybersecurity Track",
  "CMSC DATASCI": "Computer Science-Data Science Track",
  "CMSC EDUC": "Computer Science-Education Track",
  "CMSC MACHINE": "Computer Science-Machine Learning Track",
  "CMSC QUANTUM": "Computer Science-Quantum Information",
  "COM-AGRI-VET": "Combined-Agricultural and Veterinary Medicine",
  "COMM": "Communication",
  "COMM HEALTH": "Community Health",
  "COMP ENGIN": "Engineering: Computer",
  "COMP ENGR": "Computer Engineering",
  "COMPTNL SCI": "UG Certif: Computational Science",
  "COMPUTER SCI": "Computer Science",
  "CONCURRENTHS": "Concurrent HS",
  "CONSTR PM": "Construction Project Management",
  "CREATIVE WRT": "Creative Writing",
  "CRIM-JUSTICE": "Criminology and Criminal Justice",
  "CRIMJUST": "Criminal Justice",
  "CRTVPLACEMKG": "Creative Placemaking",
  "CY PHYS PRE": "Cyber-Physical Systems Engineering-PRE-MAJOR",
  "CYBRPHYSENGR": "Cyber-Physical Systems Engineering",
  "DANCE": "Dance",
  "DATA SCIENCE": "Data Science",
  "DEMOGRAPHY": "Demography",
  "DIGSTORYPOET": "Digital Storytelling and Poetics",
  "DISABLTYSTDY": "Disability Studies",
  "EARTH HIST": "Earth History",
  "EARTH MATER": "Earth Material Properties",
  "EAST ASIAN": "UG Certif: East Asian Studies",
  "EC-ECSE-PRE": "Early Childhood and EC Special Education (Pre)",
  "EC-ECSE-PRO": "Early Childhood and EC Special Education",
  "ECONOMICS": "Economics",
  "ECONOMICS-BS": "Economics-B.S.",
  "ED-ELEM-PRE": "Elementary Education (Pre)",
  "ED-ELEM-PRO": "Elementary Education",
  "ED-SPEC-PRE": "Special Education (Pre)",
  "ED-SPEC-PRO": "Special Education",
  "EDS-ART-PRE": "Secondary Educ: Art (Pre)",
  "EDS-ART-PRO": "Secondary Educ: Art Education",
  "EDS-ENGL-PRE": "Secondary Educ: English Language Arts (Pre)",
  "EDS-ENGL-PRO": "Secondary Educ: English Language Arts",
  "EDS-LANG-PRE": "Secondary Educ: World Language Education (Pre)",
  "EDS-LANG-PRO": "Secondary Educ: World Language Education",
  "EDS-MATH-PRE": "Secondary Educ: Mathematics (Pre)",
  "EDS-MATH-PRO": "Secondary Educ: Mathematics",
  "EDS-SCI-PRE": "Secondary Educ: Science (Pre)",
  "EDS-SCI-PRO": "Secondary Educ: Science",
  "EDS-SS-PRE": "Secondary Educ: Social Studies (Pre)",
  "EDS-SS-PRO": "Secondary Educ: Social Studies",
  "EDUC-UNDECID": "Undecided Teacher Education",
  "ENGIN-UNDECI": "Engineering: Undecided",
  "ENGLISH": "English",
  "ENGR-AEROSP": "Engineering: Aerospace",
  "ENGR-CHEM": "Engineering: Chemical",
  "ENGR-CIVIL": "Engineering: Civil",
  "ENGR-ELEC": "Engineering: Electrical",
  "ENGR-FIRE": "Engineering: Fire Protection (online)",
  "ENGR-MECH": "Engineering: Mechanical",
  "ENST ECODESN": "Environmental Sci & Tech: Ecological Tech Design",
  "ENST ECOHLTH": "Environmental Sci & Tech: Ecosystem Health",
  "ENST RESMGMT": "Environmental Sci & Tech: Natural Resources Mgmt",
  "ENST SOILWTR": "Environmental Sci & Tech: Soil & Watershed Science",
  "ENST UNDEC": "Environmental Sci & Tech Undecided",
  "ENTOMOLOGY": "Entomology",
  "ENTRPRLDRSHP": "Entrepreneurial Leadership",
  "ENV S&P-BIOD": "Environmental Sci & Pol-Biodvrsity & Conserv Bio",
  "ENV S&P-CULT": "Environmental Sci & Pol-Culture and the Environmnt",
  "ENV S&P-EAGR": "Environmental Sci & Pol-Environment & Agriculture",
  "ENV S&P-ECON": "Environmental Sci & Pol-Env Economics",
  "ENV S&P-ERTH": "Environmental Sci & Pol-Earth Surface Proc",
  "ENV S&P-GEO": "Environmental Sci & Pol-Env Geosci and Restoration",
  "ENV S&P-GLOB": "Environmental Sci & Pol-Global Environmntl Change",
  "ENV S&P-JUST": "Environmental Sci & Pol-Environmental Justice",
  "ENV S&P-LAND": "Environmental Sci & Pol-Land Use",
  "ENV S&P-MARN": "Environmental Sci & Pol-Marine & Coastal Mgmt",
  "ENV S&P-PLTC": "Environmental Sci & Pol-Env Politics & Policy",
  "ENV S&P-REST": "Environmental Sci & Pol-Env Restoration & Mgmt",
  "ENV S&P-SCTY": "Environmental Sci & Pol-Society & Env Issues",
  "ENV S&P-SWLR": "Environmental Sci & Pol-Soil, Water & Land Rsrcs",
  "ENV S&P-WILD": "Environmental Sci & Pol-Wildlife Ecology & Mgmt",
  "ENV SCI&POL": "Environmental Science & Policy (Policy)",
  "ENV STWRDSHP": "Environmental Stewardship",
  "ENVIR/PARK": "Natural Resources Mgt: Envir Education & Park Mgmt",
  "EPEJ": "Education Policy, Equity, and Justice",
  "EXER PHYSIO": "Kinesiology:Exercise Physiology",
  "FAMILY HLTH": "Family Health",
  "FERMENT SCI": "Fermentation Science",
  "FINANCE": "Finance",
  "FRENCH": "French Language and Literature",
  "FRENCH STDY": "French Studies",
  "GEN BUS ADM": "General Business - Gateway",
  "GEN BUSINESS": "General Business",
  "GEN ORN HORT": "General Ornamental Horticulture",
  "GEO CMP ERTH": "Geographical Sciences: Computatnl Earth Obsvtn Sci",
  "GEO DATA SCI": "Geographical Sciences: Geospatial Data Science",
  "GEO INFO SCI": "Geographic Information Science",
  "GEO SCIENCES": "Geographical Sciences",
  "GEOCHEMISTRY": "Geochemistry",
  "GEOL GEOPHYS": "Geology-Geophysics Track",
  "GEOLEARTHENV": "Geology-Earth and Env Sciences Track",
  "GEOLOGY": "Geology",
  "GEOPHYSICS": "Geophysics",
  "GERMAN": "German Studies",
  "GERMNSTUDIES": "German Studies",
  "GLBC": "Global Culture and Thought",
  "GLBL ENGRLDR": "Global Engineering Leadership",
  "GLBLFOR PLCY": "Global and Foreign Policy",
  "GLBLTERRSTDY": "Global Terrorism Studies",
  "GLFCRS CONST": "Golf Course Construction Management",
  "GLOBAL HLTH": "Global Health",
  "GLOBL POVRTY": "Global Poverty",
  "GOLF CRS MGM": "Golf Course Management",
  "GOVT & POLIT": "Government & Politics",
  "GREEK": "Greek Language and Culture",
  "GVPT BS": "Government & Politics: B.S.",
  "HEAR+SPCH SC": "Hearing and Speech Sciences",
  "HEBRWSTUDIES": "Hebrew Studies",
  "HESP": "Hearing and Speech Sciences",
  "HESPIE": "Hearing and Speech Postbaccalaureate Program",
  "HISTORY": "History",
  "HISTTHRYARCH": "History and Theory of Architecture",
  "HUM HLTH MED": "Humanities, Health, and Medicine",
  "HUMAN DEV": "Human Development",
  "HUMAN DVLPMT": "Human Development",
  "HYDROLOGY": "Hydrology",
  "IMDM CMSC": "Immersive Media Design: Computing-B.S.",
  "IMDM EMRGCRT": "Immersive Media Design: Emerging Creatives-B.A.",
  "INDIV STUDY": "Individual Studies",
  "INFO SCI": "Information Science",
  "INFO SYS": "Information Systems-Business",
  "INFORISKETH": "Information Risk Mgmt, Ethics, and Privacy",
  "INT AG RES": "UG Certif: Intnatl Agriculture & Natural Resources",
  "INTL CONFLMG": "International Development & Conflict Mgmt",
  "INTLREL": "International Relations",
  "INTLREL BS": "International Relations-BS",
  "INTNL BUSN": "International Business",
  "ISRAEL STDY": "Israel Studies",
  "ITAL": "Italian Language and Culture",
  "ITAL STUDIES": "Italian Studies",
  "JAPANESE": "Japanese",
  "JEWISH STUDY": "Jewish Studies",
  "JOURNALISM": "Journalism: News/Editorial",
  "JWST": "Jewish Studies",
  "KINESIOLOGY": "Kinesiology",
  "KORA STDY": "Korean Studies",
  "LACS": "UG Certif: Latin American and Caribbean Studies",
  "LAND/WATER": "Natural Resources Mgt: Land & Water Mgmt",
  "LANDSCP MGMT": "Landscape Management",
  "LAT GREK PB": "Latin and Greek Postbaccalaureate Program",
  "LATINO STUDY": "U.S. Latina/o Studies",
  "LATN": "Latin Language and Literature",
  "LATNAM CARIB": "Latin American and Caribbean Studies",
  "LAW SOCIETY": "Law and Society",
  "LDRSHIP STDY": "Leadership Studies",
  "LDRSHP STDY": "UG Certif: Leadership Studies",
  "LGBTQ": "LGBTQ Studies",
  "LGBTQSTUDIES": "UG Certif: LGBTQ Studies",
  "LINGUISTICS": "Linguistics",
  "LNDSCPE ARCH": "Landscape Architecture",
  "MARKETING": "Marketing",
  "MAT SCI&ENGR": "Engineering: Materials Science",
  "MATH": "Mathematics",
  "MATH-APPLIED": "Mathematics-Applied Math track",
  "MATH-ED": "Mathematics-Secondary Ed track",
  "MATH-STAT": "Mathematics-Statistics Track",
  "MATHEMATICS": "Mathematics",
  "MECHATRN PRE": "Mechatronics Engineering-PRE-MAJOR",
  "MECHATRNENGR": "Mechatronics Engineering",
  "MEDIATECHDEM": "Media, Technology and Democracy",
  "METEOROLOGY": "Meteorology",
  "MGMT": "Management",
  "MGMT ENTR": "Management-Entrepreneurship",
  "MID EAST STD": "Middle East Studies",
  "MILITARYSTDY": "Military Studies",
  "MSE": "Middle School Education",
  "MSE PRE": "Middle School Education (Pre)",
  "MTAP": "Maryland Transfer Advantage Program",
  "MUS LIB": "Music (Liberal Arts Program)",
  "MUS LIB JAZZ": "Music (Jazz Performance Option)",
  "MUS LIB PIAN": "Music (Piano Performance Option)",
  "MUS LIB STR": "Music (Strings Performance Option)",
  "MUS LIB VOIC": "Music (Voice Performance Option)",
  "MUS LIB WNDS": "Music (Winds & Percussions Performance Option)",
  "MUS PROF": "Music (Professional Program)",
  "MUS PROF CMP": "Music Composition",
  "MUS PROF JAZ": "Music Performance-Jazz Studies",
  "MUS PROF PIA": "Music Performance-Piano",
  "MUS PROF STR": "Music Performance-Strings",
  "MUS PROF THE": "Music Theory and Composition",
  "MUS PROF VOI": "Music Performance-Voice",
  "MUS PROF WND": "Music Performance-Winds and Percussion",
  "MUSIC CULTUR": "Music and Culture",
  "MUSIC ED": "Music Education",
  "MUSIC PERFOR": "Music Performance",
  "NANO TECH": "Nanoscale Science and Technology",
  "NAVALSCIENCE": "Naval Science",
  "NEURO BEHAV": "Neuroscience: Behavioral & Cognitive Track",
  "NEURO MOLEC": "Neuroscience: Molecular, Cellular, & Physio Track",
  "NEUROSCIENCE": "Neuroscience",
  "NFSC DIET": "Nutrition and Food Science: Dietetics",
  "NFSC FOODSCI": "Nutrition and Food Science: Food Science",
  "NFSC NUTRN": "Nutrition and Food Science: Nutritional Science",
  "NONPRFLDRSHP": "Nonprofit Leadership and Social Innovation",
  "NUCLEAR ENGR": "Nuclear Engineering",
  "OM BA": "Operations Management and Business Analytics",
  "PALEOBIOLOGY": "Paleobiology",
  "PERSIAN": "Persian Studies",
  "PERSIAN STDY": "Persian Studies",
  "PHILOSOPHY": "Philosophy",
  "PHILPOLIECON": "Philosophy, Politics, and Economics",
  "PHYS ED": "Physical Education",
  "PHYS-APPL": "Physics-Applied",
  "PHYS-BIOPHYS": "Physics-Biophysics",
  "PHYS-EDUC": "Physics-Education",
  "PHYSICS": "Physics",
  "PLANET SCI": "Planetary Sciences",
  "PLANT/WILD": "Natural Resources Mgt: Plant & Wildlife Mgmt",
  "PLSC BIOL": "Plant Sciences: Plant Biology",
  "PLSC FOREST": "Plant Sciences: Urban Forestry",
  "PLSC HORT": "Plant Sciences: Horticulture & Crop Production",
  "PLSC TURF": "Plant Sciences: Turf & Golf Course Mgmt",
  "PORT BRAZLN": "Portuguese and Brazilian Studies",
  "PRE-DENT": "Combined Program-Dentistry",
  "PRE-LAW": "Combined Program-Law",
  "PRE-VET MED": "Pre-Veterinary Medicine",
  "PROF WRITING": "Professional Writing",
  "PROJ MGMT": "Project Management",
  "PSCI": "Physical Sciences",
  "PSIT": "Public Service Interpreting and Translation",
  "PSYCH BS": "Psychology-B.S.",
  "PSYCHOLOGY": "Psychology",
  "PUB HLTH SCI": "Public Health Science",
  "PUB LDRSHIP": "Public Leadership",
  "PUB POLICY": "Public Policy",
  "PUBHLTH PRAC": "Public Health Practice",
  "QSE": "Quantum Science and Engineering",
  "RAS": "Robotics and Autonomous Systems",
  "RE DEVLOP": "Real Estate Development",
  "REALEST BENV": "Real Estate and the Built Environment",
  "RELANCMIDEAS": "Religions of the Ancient Middle East",
  "RELIG STUDY": "Religious Studies",
  "RHETORIC": "Rhetoric",
  "ROMA LANG": "Romance Languages",
  "RUSS STUDY": "Russian Studies",
  "RUSSIAN": "Russian Language and Literature",
  "SDSC": "Social Data Science",
  "SDSC AFAMST": "Social Data Science-African American Studies",
  "SDSC ANTH": "Social Data Science-Anthropology",
  "SDSC ECON": "Social Data Science-Economics",
  "SDSC GEOG": "Social Data Science-Geographical Sciences",
  "SDSC GVPT": "Social Data Science-Government and Politics",
  "SDSC PSYC": "Social Data Science-Psychology",
  "SDSC PUBHLTH": "Social Data Science-Public Health",
  "SDSC SOCY": "Social Data Science-Sociology",
  "SECOND ED": "UG Certif: Secondary Education",
  "SECOND EDUC": "Secondary Education",
  "SENS ENV CH": "Remote Sensing of Environmental Change",
  "SIE": "Life Science Postbaccalaureate Program",
  "SOCIOLOGY": "Sociology",
  "SOCY": "Sociology",
  "SOIL SCIENCE": "Soil Science",
  "SPAN1LITCULT": "Span Minor 1: Literature,Linguistics,Cultur",
  "SPAN2LANGPRO": "Span Minor 2: Lang, Culture,Profssnl Cntxts",
  "SPAN3HERITAG": "Span Minor 3: Heritage Lang Latino/a Cultr",
  "SPANISH": "Spanish Language, Literatures, and Cultures",
  "SPEC EDUC": "Special Education",
  "SPHL UNDECID": "SPHL Undecided",
  "SPORT": "Sport Commerce and Culture",
  "SPORT TURF": "Sports Turf Management",
  "SPRTCOMMCULT": "Kinesiology:Sport, Commerce, & Culture",
  "STATISTICS": "Statistics",
  "STEP": "Science, Technology, Ethics and Policy",
  "SUPP CH MGMT": "Supply Chain Management",
  "SURFIC GEOL": "Surficial Geology",
  "SURV METHOD": "Survey Methodology",
  "SUSTAIN AG": "Sustainable Agriculture",
  "SUSTAIN STDY": "Sustainability Studies",
  "TECH ENTRPNR": "Tech Entrepreneurship & Corporate Innovatn",
  "TECHINFODESN": "Technology and Information Design",
  "TECHINNOVLDR": "Technology Innovation Leadership (online)",
  "TERPS-EXCEED": "Terps-EXCEED",
  "TESOLDUALANG": "Tchg Engl for Spkrs of Oth Lang&Dual Lang Ed",
  "THEATRE": "Theatre",
  "TRFGRASS MGM": "General Turfgrass Management",
  "UMB NURSING": "Nursing (UMB Program)",
  "URB FOR MGMT": "Urban Forest Management",
  "VEP": "Veterans Pathways Program",
  "VIDEODOCUMNT": "Video Production and Documentary Filmmaking",
  "WGSS": "Women, Gender, and Sexuality Studies",
  "WMNGNDRSXLTY": "Women, Gender, and Sexuality Studies"
};

export const SCHOOL_CODE_TO_NAME: Record<string, string> = {
  "AGNR": "Agriculture and Natural Resources",
  "ARCH": "School of Architecture, Planning and Preservation",
  "ARHU": "Arts and Humanities",
  "BMGT": "The Robert H. Smith School of Business",
  "BSOS": "Behavioral and Social Sciences",
  "CMNS": "Computer, Mathematical, and Natural Sciences",
  "EDUC": "Education",
  "ENGR": "The A. James Clark School of Engineering",
  "INFO": "Information",
  "JOUR": "Philip Merrill College of Journalism",
  "PLCY": "Public Policy",
  "SPHL": "School of Public Health",
  "UGST": "Undergraduate Studies"
};
